POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "firstname": "Duc Anh",
  "lastname": "Nguyen",
  "email": "ducanhnguyen.ldb@gmail.com",
  "password": "ducanh"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "ducanhnguyen.ldb@gmail.com",
  "password": "ducanh"
}